# -*- coding: utf-8 -*-
"""SkyLearn-LinearRegression_Exer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11PY67lOr2FchW98Y-QxFS76BYcNrPr9E

##**Codelab**
Pertama kita mengimpor library yang diperlukan. Lalu buat data dummy menggunakan numpy array.
"""

import numpy as np

#buat data jumlah kamar
bedrooms = np.array([1,1,2,2,3,4,4,5,5,5])

#data harga rumah. Asumsi dalam dollar
house_price = np.array([15000, 18000, 27000, 34000, 50000, 68000, 65000, 81000,85000, 90000])

"""#####Selanjutnya, kita bisa mencoba menampilkan data tersebut dalam bentuk scatter plot. Jumlah kamar pada sumbu X adalah variabel independen dan harga rumah pada sumbu Y  adalah variabel dependen."""

# Commented out IPython magic to ensure Python compatibility.
#menampilkan scatter plot dari dataset

import matplotlib.pyplot as plt
# %matplotlib inline
print("Tampilan dari kode tersebut sebagai berikut:")
plt.scatter(bedrooms, house_price)

"""#####Lalu pada cell berikutnya, kita bisa mulai melatih model kita dengan memanggil fungsi LinearRegression.fit() pada data kita. Fungsi ini untuk melatih model regresi linier dari library SKLearn."""

from sklearn.linear_model import LinearRegression

#latih model dengan Linear Regression
bedrooms = bedrooms.reshape(-1,1)
linreg = LinearRegression()
linreg.fit(bedrooms, house_price)

"""#####Terakhir kita bisa melihat bagaimana model kita menyesuaikan dengan data yang kita miliki dengan membuat plot dari model kita."""

# menampilkan plot hubungan antara jumlah kamar dengan haraga murah
plt.scatter(bedrooms, house_price)
plt.plot(bedrooms, linreg.predict(bedrooms))

"""######Model regresi linier adalah salah satu model machine learning yang paling sederhana. Model ini memiliki kompleksitas rendah dan bekerja sangat baik pada dataset yang memiliki hubungan linier. Jadi, ketika Anda menemui masalah yang terlihat memiliki hubungan linier, regresi linier dapat menjadi pilihan pertama sebagai model untuk dikembangkan."""